spring:
  redis:
    host: xxx.xxx.xxx.xxx
    password: redis
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
    timeout: 10000